{{- range .Values.versionChecker.allowedNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "version-checker.name" . }}
  namespace: .
subjects:
- kind: ServiceAccount
  name: {{ include "version-checker.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "version-checker.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}  
