{{- if not .Values.secrets.existingSecret | empty -}}
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.secrets.auth.name }}
spec:
    path: {{ .Values.secrets.auth.path }}
    type: Opaque
{{- end -}}
