# Настройки проверки образов
namespace_list:
  - "default"
  - "kube-system"

images:
  - name: "quay.io/keycloak/keycloak-operator"
    desired_tag: "24.0.5"
    # pined_major: 23
    # resolve_sha256:
    #   - tag: "23.0.5"
    #     hash: "sha256:2b4729e4a4f..."
    #   - tag: "23.0.4"
    #     hash: "sha256:3e830a1a1d4..."
  - name: "ghcr.io/cloudnative-pg/postgresql"
    desired_tag: "17.4"
    # resolve_sha256:
    #   - tag: "1.25.3"
    #     hash: "sha256:9825d..."
  - name: quay.io/prometheus/node-exporter
    desired_tag: v1.7.1
    resolve_sha256:
      - tag: v1.9.1
        hash: "sha256:d00a542e409ee618a4edc67da14dd48c5da66726bbd5537ab2af9c1dfc442c8a"

# Настройки подключения к registry
registry:
  url: "https://quay.io/v2"
  auth_type: "token"  # или "basic"

shedule: '*/2 * * * *'
